language: node_js
node_js:
- '5'
env:
  global:
    secure: mvmiYYQ2TCGYoKYMEesbj69Gmjh9iseMLL4RdM79BWwSSulB95A5uEZ4lwbX1gavGg9DjxAhvuoxVHhCg0UeJuzqTRhFsiq8HcslrlcKE7Oyq5ZlHEVUMvmswgXbeT4Z/yhbatdHNBgY7bn4vlSTLFDyjD7mFiJ3jfkQlL3+47dcycEBng7yUuG2j8xMWR9FENaVez4uamOSbEFF6ix2Bu+X3Y7o20/GKH0f66xSX0qcwbH9yazsfFXtGsn3pNsf4A/8+vwNu+7FaxCVMKa+1rldmRm51XsekLgHUH5UNY1AJ3N3XiSNoUlw7elBBg+LkZ/9ImGk76TkAbn5/24WulWWD5hQbdEAsGzqPALEjCDyGXI/K5bRNvBwq7MzYAMvv9E3/dULf877/XYqoV+c2PzjQdZO/LRJm/yQVQNCg5Zf3ULVsp8iYc+ZaeSl8+Z1o6DxuYWnqdTnDO3kEcI60V5jZZRajmI0PLULNuYgmvFJdp2obPbPadzZPZx63ow/BshSKr30YE1F/QTTe6Bfgyaanl5SSOiVmOkUv0iO4iv4/yU+u6zyMeP3tqeQPz+iScffg+FmjfVhqhuaxFs5moIWz8YFXes4/efsoRsxAyM0Bghnts/LITcloWD0CQQX5lzQgKEEumfxFQrKj3Nc8euekWsAGdlOCxisDgrGf98=
